#!/usr/bin/env python3
"""
Generate the synthetic data WITHOUT a database, as:
  sql/03_seed_data.sql  INSERT script (timestamps are relative to now(), so it is always fresh)
  data/*.csv            one CSV per table (absolute timestamps, goes stale after ~a week)

ALL DATA IS FAKE. Same generators and seed as seed_data.py. Needs only Python, no pip install.
Usage: python scripts/export_data.py
"""
import csv
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import seed_data as sd  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
BATCH = 500


def plain(v):
    return v.adapted if hasattr(v, "adapted") else v


def sql_val(v):
    v = plain(v)
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, datetime):
        secs = round((sd.NOW - v).total_seconds())
        return f"now() - interval '{secs} seconds'" if secs >= 0 else f"now() + interval '{-secs} seconds'"
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


def csv_val(v):
    v = plain(v)
    if v is None:
        return ""
    if isinstance(v, datetime):
        return v.isoformat()
    if isinstance(v, (dict, list)):
        return json.dumps(v, ensure_ascii=False)
    return v


def main():
    users = sd.make_users(700, 150)
    tenders = sd.make_tenders([u for u in users if u["role"] == "gc"])
    events = sd.make_events(users, tenders)
    enrich, crm, calls, supp = sd.make_aux(users)
    tables = [
        ("users", ["id", "role", "company_name", "email", "trade", "region", "company_size", "language", "plan",
                   "signup_at", "paid_at"],
         [(u["id"], u["role"], u["company_name"], u["email"], u["trade"], u["region"], u["company_size"],
           u["language"], u["plan"], u["signup_at"], u["paid_at"]) for u in users]),
        ("tenders", ["id", "gc_user_id", "title", "trade", "region", "value_eur", "posted_at", "deadline", "status"],
         [(t["id"], t["gc_user_id"], t["title"], t["trade"], t["region"], t["value_eur"], t["posted_at"],
           t["deadline"], t["status"]) for t in tenders]),
        ("events", ["user_id", "event_type", "tender_id", "occurred_at", "properties"], events),
        ("company_enrichment", ["user_id", "employee_count", "revenue_band", "founded_year", "fit_score"], enrich),
        ("crm_accounts", ["user_id", "owner", "stage", "open_opportunity", "arr_eur", "last_activity_at", "notes"], crm),
        ("call_notes", ["user_id", "called_at", "transcript", "extracted"], calls),
        ("suppressions", ["user_id", "reason"], supp),
    ]
    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    with open(os.path.join(ROOT, "sql", "03_seed_data.sql"), "w", encoding="utf-8") as out:
        out.write("-- Generated by scripts/export_data.py. ALL DATA IS FAKE. Run after 01 and 02.\n")
        for name, cols, rows in tables:
            out.write(f"\n-- {name}: {len(rows)} rows\n")
            for i in range(0, len(rows), BATCH):
                chunk = rows[i:i + BATCH]
                vals = ",\n".join("(" + ", ".join(sql_val(v) for v in r) + ")" for r in chunk)
                out.write(f"INSERT INTO {name} ({', '.join(cols)}) VALUES\n{vals};\n")
            with open(os.path.join(ROOT, "data", f"{name}.csv"), "w", newline="", encoding="utf-8") as f:
                w = csv.writer(f)
                w.writerow(cols)
                for r in rows:
                    w.writerow([csv_val(v) for v in r])
            print(f"{name}: {len(rows)} rows")


if __name__ == "__main__":
    main()
